version: "3"

services:
    mysql:
        container_name: shop_mysql
        image: varlive/mysql:5.7

        volumes:
            - ./data:/var/lib/mysql
            - ./mysql:/etc/mysql

        restart: always

        environment:
            MYSQL_ROOT_PASSWORD : 12345678

        ports:
            - "3308:3306"
        networks:
            - mysql

networks:
    mysql: